### PR TITLE
Support polyfill being constructed after DOMContentLoaded event

### PR DESCRIPTION
**Pull request by RSpace**

### CODE REVIEW

**Comment by blairmacintyre** [comment]
Seems like a good change.  @arturitu what do you think?

**Comment by arturitu** [comment]
Yes, is a good change.

**Comment by RSpace** [comment]
Thanks for merging! I'll wait for this to make it's way into `aframe-xr` via `three.xr.js`.  Bit of a complicated path, but guess there's not helping it at this point.

**Comment by blairmacintyre** [comment]
@arturitu I saw you merged some other PR's on three.xr.js and aframe-xr ... did you rebuild those libraries as a result, and do they include this latest update?

**Pull request merged**
