### PR TITLE
Support camera passthrough on WebARonARKit (develop)

### PR DESCRIPTION
**Pull request by machenmusik**
Per Blair:
For now our “process” is to have work done in develop first and then moved to master — so I’d like to pull into develop and test it myself and then merge over.

From #66:
WebARonARKit exposes the same WebAR API as WebARonARCore, but implements camera rendering separately. So, when we detect WebARonARKit (by checking for the main window method it uses), we don't do the ARCore camera rendering, but still do the WebAR updating.

### CODE REVIEW

**Comment by blairmacintyre** [comment]
Doens't anything need to change up in the constructor?  We don't need to be creating `this._arCoreCanvas` for the ARKit version, but it seems like it would.

**Comment by machenmusik** [comment]
I wasn't sure the side effects from larger changes like that were safe.  If you're saying they are, then yes I can make that be conditional

**Comment by blairmacintyre** [comment]
I'm saying I don't know. :)

I think your basic changes are correct;  but there are a few places that need to be adjusted to take it into account.  At the very least, the constructor shouldn't create and insert that extra canvas unless it's use (WebARonARCore, but not WebARonARKit).  I found a few other places in the code that refer to "ARCore" that probably just need comments updated.

I'm mostly just concerned that we dot all the i's and cross the t's.  So that when people look at the code it makes sense in the future (e.g., we had some assumptions built in about ARCore, you fixed it for ARKit, but there is still some clarity needed).  I am traveling today and in meetings, so I can't fix it, but hopefully we'll get it all integrated this week.  We definitely want to handle this situation correctly!

**Comment by machenmusik** [comment]
Thanks, that makes sense.  Let me know if you need me to make any further changes here, it sounds like you are going to take this one over from here.

**Comment by blairmacintyre** [comment]
I'm going to merge and add a few fixes.

**Pull request merged**
